name = "rgb_glitch"
display_name = "RGB Glitch"
min_gles = "1.00"

[[params]]
slot = 0
name = "r_off"
min = -1.0
max = 1.0
default = 0.5
curve = "linear"

[[params]]
slot = 1
name = "g_off"
min = -1.0
max = 1.0
default = -0.5
curve = "linear"

[[params]]
slot = 2
name = "b_off"
min = -1.0
max = 1.0
default = 0.5
curve = "linear"

[[params]]
slot = 3
name = "speed"
min = 0.0
max = 1.0
default = 0.3
curve = "linear"
